# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.CharField(max_length=32, unique=True)),
                ('target_url', models.CharField(max_length=4096)),
            ],
        ),
    ]
